### PR TITLE
Update deprecated shim package

### LINKED ISSUE #47: Storybook 8 Support
I've seen this [migration guide](https://storybook.js.org/docs/8.0/addons/addon-migration-guide#key-changes-for-addons) floating about for Storybook 8 support, not sure if there's any changes required for wc-storybook-helpers, but would be great to have support for it close after it launches!

### PR DESCRIPTION
**Pull request by nkabrown**
Fixes #47 

As of Storybook v8 the `@storybook/client-api` package has been removed and incorporated into `@storybook/preview-api`. Update the `useArgs` import statement.

### CODE REVIEW

**Comment by nkabrown** [comment]
See this section of the v8 migration guide: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#removed-deprecated-shim-packages

**Comment by break-stuff** [comment]
Is this API in v7 as well? I would like to maintain backwards compatibility with it, if we can.

**Comment by nkabrown** [comment]
This API was added to `@storybook/preview-api` when v7.0.0 was released. Here is the relevant section from the 6 to 7 migration guide.

"You might also depend (and use) these packages in your addon's decorators: @storybook/store, @storybook/preview-web, @storybook/core-client, @storybook/client-api; these have all been consolidated into @storybook/preview-api. So if you use any of these packages, please import what you need from @storybook/preview-api instead."

**Comment by break-stuff** [comment]
You are awesome! Thanks!

**Comment by break-stuff** [comment]
The only downside is that this will introduce a breaking change because we are dropping v6 support. I'm totally ok with that, but I need to plan accordingly.

**Review by break-stuff — APPROVED** [review]

**Pull request merged**
